- name: WandbCallback
  configs:
    project: explainable-medical-coding
    entity: null
- name: SaveBestModelCallback
  configs:
    split: validation
    target: all
    metric: f1_combined
- name: EarlyStoppingCallback
  configs:
    split: validation
    target: all
    metric: f1_combined
    patience: 6