name: PLMICD
autoregressive: false
configs:
  model_path: models/modernbert-base
  chunk_size: 128
  cross_attention: true
  attention_type: "label"  # "label", "token_level"
  loss: binary_cross_entropy
  lambda_1: 0.0
  scale: 1
  mask_input: false
  use_peft: false
  freeze_label_embeddings: false
  init_with_descriptions: false
